### ISSUE TITLE
Add support for React v18

### ISSUE THREAD

**Issue by chadalen** [Pyrax/react-netlify-forms#50]
Peer dep only supports v16 and v17 add support for v18
[see here
](https://github.com/Pyrax/react-netlify-forms/blob/master/package.json#L41)
![image](https://user-images.githubusercontent.com/12568665/187805377-8d187700-e08b-42a1-a7ae-0659cd2ce210.png)

**Comment by Pyrax** [comment]
Thanks for reporting.
I've successfully tested against React 18 and added support now :tada:
